import csv
import random

classes = ["Schedule","Reschedule", "Cancel", "Show Status","Greet", "Not well"]

text_samples = {
    "Schedule" : [
    "Can we schedule an appointment for today?",
    "I would like to schedule a meeting for tomorrow.",
    "Could you please book an appointment for Monday?",
    "I'm interested in setting up a meeting on Tuesday.",
    "Is it possible to arrange an appointment for Wednesday?",
    "I need to schedule an appointment for Thursday.",
    "Let's plan a meeting for Friday.",
    "Can you find time for an appointment next week?",
    "I'm available today. Can we meet?",
    "I'm free tomorrow afternoon. Can we schedule an appointment?",
    "I'd like to book a meeting for the day after tomorrow.",
    "I have some time on Monday. Can we meet then?",
    "I'm interested in scheduling an appointment for Tuesday morning.",
    "Can we set up a meeting for Wednesday afternoon?",
    "I'm only available on Thursdays. Can we schedule it then?",
    "I prefer Fridays for appointments. Is that possible?",
    "Let's plan a meeting for next Wednesday.",
    "I'm flexible with the time. Please choose a suitable day.",
    "I'd like to meet either today or tomorrow. Can you arrange it?",
    "I'm looking for an appointment on any weekday this week.",
],
    "Reschedule": [
        "Can we reschedule my appointment for tomorrow?",
        "I need to change my meeting date.",
        "Please move my reservation to a later time.",
        "Is it possible to change my appointment to next week?",
        "I can't make it on the scheduled date. Can we change it?",
        "I need to move my meeting to a different date.",
        "Can we reschedule my conference call to Friday?",
        "I want to change the time of my appointment.",
        "I need to move my reservation to a later time slot.",
        "Can we move my appointment to a different day?",
        "Can we reschedule my dental appointment for next Monday?",
        "I have a conflict on the appointment date. Can we change it to the 15th?",
        "Please move my meeting to a later time in the afternoon.",
        "I want to move my reservation to the morning slot.",
        "Is it possible to change my appointment to a different location?",
        "Can we reschedule my conference call to the same time next week?",
        "I need to change my appointment time to 3 PM.",
        "I can't make it on the scheduled date. Can we reschedule it for later in the week?",
        "Can you move my appointment to a different day and time?",
        "I want to postpone my reservation to a later date.",
        "My current appointment conflicts with another event. Can we reschedule?",
        "I need to change my meeting to Tuesday morning.",
        "Can we move my appointment to a different branch?",
        "I want to reschedule my conference call to Wednesday afternoon.",
        "Please change my reservation to a time slot that works for me.",
        "I have a scheduling conflict. Can we move my appointment to Thursday?",
        "Is it possible to postpone my appointment to the end of the month?",
        "I need to change the time of my reservation to later in the evening.",
        "Can we reschedule my appointment for the 25th of this month?",
        "I can't make it on the scheduled date. Can we find another time?",
        "I want to move my meeting to a different day of the week.",
        "Please change my reservation to a later time in the day.",
        "I have an emergency and need to reschedule my appointment.",
        "Can we reschedule my conference call to a time that suits everyone?",
        "I need to change my appointment to the morning.",
    ],
    "Cancel": [
        "I need to cancel my appointment on Friday.",
        "Cancel my meeting for tomorrow.",
        "I need to cancel my dentist appointment for next Monday.",
        "I won't be able to make it to the appointment on Friday. Please cancel it.",
        "Cancel my reservation for tomorrow's meeting.",
        "Unfortunately, I need to cancel my reservation for the morning slot.",
        "I can't make it to the appointment at a different location. Please cancel it.",
        "Cancel my conference call for the same time next week.",
        "I have to cancel my appointment scheduled for 3 PM.",
        "I can't make it on the scheduled date. Please cancel it and find another time.",
        "Please cancel my appointment for a different day and time.",
        "I need to cancel my reservation for a later date.",
        "My current appointment conflicts with another event. Please cancel it.",
        "I need to cancel my meeting on Tuesday morning.",
        "Cancel my appointment at a different branch.",
        "I want to cancel my conference call for Wednesday afternoon.",
        "Please cancel my reservation as it doesn't work for me anymore.",
        "I have a scheduling conflict. Please cancel my appointment for Thursday.",
        "I need to postpone my appointment to the end of the month or cancel it.",
        "I need to cancel the reservation for later in the evening.",
        "Cancel my appointment for the 25th of this month.",
        "I can't make it on the scheduled date. Please cancel and reschedule.",
        "Please cancel my meeting for a different day of the week.",
        "I have an emergency and need to cancel my appointment.",
        "Cancel my conference call for a time that suits everyone.",
        "I need to cancel my appointment for the morning.",
    ],
    "Show Status": [
        "Show me the appointment status.",
        "What's the status of my reservation?",
        "Can you show me the status of my upcoming appointment for tomorrow?",
        "What's the status of my dental appointment on Friday?",
        "Please provide the status of my reservation for tomorrow's meeting.",
        "I'd like to know the status of my appointment for the morning slot.",
        "Can you show me the status of my appointment at a different location?",
        "Show me the status of my conference call for the same time next week.",
        "I want to check the status of my appointment scheduled for 3 PM.",
        "Is there any update on the status of my appointment? I can't make it on the scheduled date.",
        "Can you provide the status of my appointment for a different day and time?",
        "I'm curious about the status of my reservation for a later date.",
        "Please check the status of my meeting as it conflicts with another event.",
        "I need to know the status of my meeting on Tuesday morning.",
        "Could you please show me the status of my appointment at a different branch?",
        "I'd like to check the status of my conference call for Wednesday afternoon.",
        "Show me the status of my reservation and confirm if it still works for me.",
        "I have a scheduling conflict. Can you update me on the status of my appointment for Thursday?",
        "Is it possible to postpone my appointment to the end of the month? Please check the status as well.",
        "I need to change the time of my reservation. Please show me the updated status.",
        "Can you show me the status of my appointment for the 25th of this month?",
        "I can't make it on the scheduled date. Can you show me the status and suggest another time?",
        "Please show me the status of my meeting for a different day of the week.",
        "I have an emergency and need to confirm the status of my appointment.",
        "Show me the status of my conference call and make sure it suits everyone's availability.",
        "I need to change the time of my appointment and would like to see the updated status.",
    ],
    "Greet": [
        "Hii",
        "Heyy",
        "Hello",
        "Hi",
        "Good Morning",
        "Good Evening",
        "Howdy",
        "Hey there",
        "Hiya",
        "Hola",
        "Bonjour",
        "Ciao",
        "Salaam",
        "Namaste",
        "Konnichiwa",
        "Ohayou gozaimasu",
        "Zdravstvuyte",
        "Merhaba",
        "Selamat pagi",
        "Xin chào",
        "Moin moin",
        "Servus",
        "Grüß Gott",
        "Mabuhay",
    ],
    "Not well": [
        "I'm not feeling well today.",
        "I feel sick.",
        "I'm under the weather.",
        "I don't feel good.",
        "I'm not at my best.",
        "I'm feeling unwell.",
        "I think I might be coming down with something.",
        "I have a headache.",
        "I have a fever.",
        "I'm feeling nauseous.",
        "I'm dizzy.",
        "I have a sore throat.",
        "I have a cough.",
        "I'm tired and achy.",
        "I have chills.",
        "I'm not up to par.",
        "I'm feeling weak.",
        "I'm exhausted.",
        "I'm running a temperature.",
        "I have body aches.",
        "I'm shivering.",
        "I'm not in great shape.",
        "I'm feeling feverish.",
        "I'm queasy.",
        "I'm vomiting.",
        "I have an upset stomach.",
        "I'm feeling lightheaded.",
        "I'm not feeling myself.",
        "I'm in pain.",
        "I'm feeling awful.",
        "I'm feeling dreadful.",
        "I'm not in the mood.",
        "I'm feeling miserable.",
        "I'm feeling terrible.",
        "I'm feeling down.",
        "I'm feeling off.",
        "I'm not up to doing anything.",
        "I'm feeling really bad.",
        "I'm feeling awful.",
    ]
}

# Shuffle and create a balanced dataset
dataset = []

for class_name in classes:
    for sample in text_samples[class_name]:
        dataset.append([sample, class_name])

# Shuffle the dataset again to randomize class order
random.shuffle(dataset)

# Specify the CSV file name
csv_filename = "classification_dataset.csv"

# Write the data to the CSV file
with open(csv_filename, mode="w", newline="",encoding="utf-8") as file:
    writer = csv.writer(file)
    writer.writerow(["User Text", "Intent"])  # Write the header
    writer.writerows(dataset)

print(f"CSV file '{csv_filename}' with a balanced dataset generated successfully.")
